spring.application.name=LearnerManagementSystemBELC20
server.port=1000

spring.datasource.url=jdbc:h2:mem:LearnerManagementSystemC20
spring.datasource.username=user
spring.datasource.password=user
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

